version: '3.7'
services:
  docker:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 18er0821
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017